stages:
- deploy
deploy_production:
 stage: deploy
 script:
 - cd /var/www/rincondeantonia.cl/public_html/wp-content/themes/onecart
 - pwd
 - whoami
 - git pull
 only:
 - master
 tags:
 - production    